AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB table for loopitProject with only PK and SK defined in schema.

Resources:
  LoopitProjectTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "loopitProject"

      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      DeletionProtectionEnabled: true

Outputs:
  LoopitProjectTableName:
    Description: The name of the new DynamoDB table
    Value: !Ref LoopitProjectTable
    Export:
      Name: Loopit-DynamoTableName

  LoopitProjectTableArn:
    Description: The ARN of the new DynamoDB table
    Value: !GetAtt LoopitProjectTable.Arn
    Export:
      Name: Loopit-DynamoTableArn
