Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Architectures:
      - x86_64
    Timeout: 200
    Handler: bootstrap
    Runtime: provided.al2023

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  Login:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-handler/login
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /auth/login
            RestApiId: !Ref Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Loopit-DynamoTableName

  register:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-handler/register
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /auth/register
            RestApiId: !Ref Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Loopit-DynamoTableName

  #  Category Lambdas
  CreateCategory:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-handler/categories/create
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /categories
            RestApiId: !Ref Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Loopit-DynamoTableName

  GetAllCategories:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-handler/categories/get
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /categories
            RestApiId: !Ref Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Loopit-DynamoTableName

  UpdateCategory:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-handler/categories/update
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: put
            Path: /categories/{id}
            RestApiId: !Ref Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Loopit-DynamoTableName

  DeleteCategory:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-handler/categories/delete
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /categories/{id}
            RestApiId: !Ref Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Loopit-DynamoTableName
