// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	models "loopit/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSocietyRepo is a mock of SocietyRepo interface.
type MockSocietyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSocietyRepoMockRecorder
}

// MockSocietyRepoMockRecorder is the mock recorder for MockSocietyRepo.
type MockSocietyRepoMockRecorder struct {
	mock *MockSocietyRepo
}

// NewMockSocietyRepo creates a new mock instance.
func NewMockSocietyRepo(ctrl *gomock.Controller) *MockSocietyRepo {
	mock := &MockSocietyRepo{ctrl: ctrl}
	mock.recorder = &MockSocietyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocietyRepo) EXPECT() *MockSocietyRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSocietyRepo) Create(society models.Society) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", society)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSocietyRepoMockRecorder) Create(society any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSocietyRepo)(nil).Create), society)
}

// FindAll mocks base method.
func (m *MockSocietyRepo) FindAll() ([]models.Society, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]models.Society)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSocietyRepoMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSocietyRepo)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockSocietyRepo) FindByID(id int) (models.Society, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(models.Society)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSocietyRepoMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSocietyRepo)(nil).FindByID), id)
}

// Save mocks base method.
func (m *MockSocietyRepo) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSocietyRepoMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSocietyRepo)(nil).Save))
}
