// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	models "loopit/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReturnRequestRepo is a mock of ReturnRequestRepo interface.
type MockReturnRequestRepo struct {
	ctrl     *gomock.Controller
	recorder *MockReturnRequestRepoMockRecorder
}

// MockReturnRequestRepoMockRecorder is the mock recorder for MockReturnRequestRepo.
type MockReturnRequestRepoMockRecorder struct {
	mock *MockReturnRequestRepo
}

// NewMockReturnRequestRepo creates a new mock instance.
func NewMockReturnRequestRepo(ctrl *gomock.Controller) *MockReturnRequestRepo {
	mock := &MockReturnRequestRepo{ctrl: ctrl}
	mock.recorder = &MockReturnRequestRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReturnRequestRepo) EXPECT() *MockReturnRequestRepoMockRecorder {
	return m.recorder
}

// CreateReturnRequest mocks base method.
func (m *MockReturnRequestRepo) CreateReturnRequest(req models.ReturnRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReturnRequest", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReturnRequest indicates an expected call of CreateReturnRequest.
func (mr *MockReturnRequestRepoMockRecorder) CreateReturnRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReturnRequest", reflect.TypeOf((*MockReturnRequestRepo)(nil).CreateReturnRequest), req)
}

// GetAllReturnRequests mocks base method.
func (m *MockReturnRequestRepo) GetAllReturnRequests(filterStatuses []string) ([]models.ReturnRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllReturnRequests", filterStatuses)
	ret0, _ := ret[0].([]models.ReturnRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllReturnRequests indicates an expected call of GetAllReturnRequests.
func (mr *MockReturnRequestRepoMockRecorder) GetAllReturnRequests(filterStatuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllReturnRequests", reflect.TypeOf((*MockReturnRequestRepo)(nil).GetAllReturnRequests), filterStatuses)
}

// GetReturnRequestByID mocks base method.
func (m *MockReturnRequestRepo) GetReturnRequestByID(id int) (models.ReturnRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReturnRequestByID", id)
	ret0, _ := ret[0].(models.ReturnRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReturnRequestByID indicates an expected call of GetReturnRequestByID.
func (mr *MockReturnRequestRepoMockRecorder) GetReturnRequestByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReturnRequestByID", reflect.TypeOf((*MockReturnRequestRepo)(nil).GetReturnRequestByID), id)
}

// Save mocks base method.
func (m *MockReturnRequestRepo) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockReturnRequestRepoMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockReturnRequestRepo)(nil).Save))
}

// UpdateReturnRequestStatus mocks base method.
func (m *MockReturnRequestRepo) UpdateReturnRequestStatus(id int, newStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReturnRequestStatus", id, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReturnRequestStatus indicates an expected call of UpdateReturnRequestStatus.
func (mr *MockReturnRequestRepoMockRecorder) UpdateReturnRequestStatus(id, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReturnRequestStatus", reflect.TypeOf((*MockReturnRequestRepo)(nil).UpdateReturnRequestStatus), id, newStatus)
}
