// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	models "loopit/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLenderRepo is a mock of LenderRepo interface.
type MockLenderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLenderRepoMockRecorder
}

// MockLenderRepoMockRecorder is the mock recorder for MockLenderRepo.
type MockLenderRepoMockRecorder struct {
	mock *MockLenderRepo
}

// NewMockLenderRepo creates a new mock instance.
func NewMockLenderRepo(ctrl *gomock.Controller) *MockLenderRepo {
	mock := &MockLenderRepo{ctrl: ctrl}
	mock.recorder = &MockLenderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLenderRepo) EXPECT() *MockLenderRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLenderRepo) Create(lender *models.Lender) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", lender)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLenderRepoMockRecorder) Create(lender interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLenderRepo)(nil).Create), lender)
}

// FindAll mocks base method.
func (m *MockLenderRepo) FindAll() ([]models.Lender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]models.Lender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockLenderRepoMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockLenderRepo)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockLenderRepo) FindByID(userID int) (*models.Lender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", userID)
	ret0, _ := ret[0].(*models.Lender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockLenderRepoMockRecorder) FindByID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockLenderRepo)(nil).FindByID), userID)
}

// Save mocks base method.
func (m *MockLenderRepo) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLenderRepoMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLenderRepo)(nil).Save))
}
