// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	models "loopit/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBuyerRequestRepo is a mock of BuyerRequestRepo interface.
type MockBuyerRequestRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBuyerRequestRepoMockRecorder
}

// MockBuyerRequestRepoMockRecorder is the mock recorder for MockBuyerRequestRepo.
type MockBuyerRequestRepoMockRecorder struct {
	mock *MockBuyerRequestRepo
}

// NewMockBuyerRequestRepo creates a new mock instance.
func NewMockBuyerRequestRepo(ctrl *gomock.Controller) *MockBuyerRequestRepo {
	mock := &MockBuyerRequestRepo{ctrl: ctrl}
	mock.recorder = &MockBuyerRequestRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuyerRequestRepo) EXPECT() *MockBuyerRequestRepoMockRecorder {
	return m.recorder
}

// CreateBuyerRequest mocks base method.
func (m *MockBuyerRequestRepo) CreateBuyerRequest(req models.BuyingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBuyerRequest", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBuyerRequest indicates an expected call of CreateBuyerRequest.
func (mr *MockBuyerRequestRepoMockRecorder) CreateBuyerRequest(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBuyerRequest", reflect.TypeOf((*MockBuyerRequestRepo)(nil).CreateBuyerRequest), req)
}

// GetAllBuyerRequests mocks base method.
func (m *MockBuyerRequestRepo) GetAllBuyerRequests(filterStatus []string) ([]models.BuyingRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBuyerRequests", filterStatus)
	ret0, _ := ret[0].([]models.BuyingRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBuyerRequests indicates an expected call of GetAllBuyerRequests.
func (mr *MockBuyerRequestRepoMockRecorder) GetAllBuyerRequests(filterStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBuyerRequests", reflect.TypeOf((*MockBuyerRequestRepo)(nil).GetAllBuyerRequests), filterStatus)
}

// GetBuyerRequestByID mocks base method.
func (m *MockBuyerRequestRepo) GetBuyerRequestByID(id int) (*models.BuyingRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuyerRequestByID", id)
	ret0, _ := ret[0].(*models.BuyingRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuyerRequestByID indicates an expected call of GetBuyerRequestByID.
func (mr *MockBuyerRequestRepoMockRecorder) GetBuyerRequestByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuyerRequestByID", reflect.TypeOf((*MockBuyerRequestRepo)(nil).GetBuyerRequestByID), id)
}

// Save mocks base method.
func (m *MockBuyerRequestRepo) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockBuyerRequestRepoMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBuyerRequestRepo)(nil).Save))
}

// UpdateStatusBuyerRequest mocks base method.
func (m *MockBuyerRequestRepo) UpdateStatusBuyerRequest(id int, newStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusBuyerRequest", id, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusBuyerRequest indicates an expected call of UpdateStatusBuyerRequest.
func (mr *MockBuyerRequestRepoMockRecorder) UpdateStatusBuyerRequest(id, newStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusBuyerRequest", reflect.TypeOf((*MockBuyerRequestRepo)(nil).UpdateStatusBuyerRequest), id, newStatus)
}
