// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	models "loopit/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFeedbackRepository is a mock of FeedbackRepository interface.
type MockFeedbackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackRepositoryMockRecorder
}

// MockFeedbackRepositoryMockRecorder is the mock recorder for MockFeedbackRepository.
type MockFeedbackRepositoryMockRecorder struct {
	mock *MockFeedbackRepository
}

// NewMockFeedbackRepository creates a new mock instance.
func NewMockFeedbackRepository(ctrl *gomock.Controller) *MockFeedbackRepository {
	mock := &MockFeedbackRepository{ctrl: ctrl}
	mock.recorder = &MockFeedbackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackRepository) EXPECT() *MockFeedbackRepositoryMockRecorder {
	return m.recorder
}

// CreateFeedback mocks base method.
func (m *MockFeedbackRepository) CreateFeedback(feedback models.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeedback", feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFeedback indicates an expected call of CreateFeedback.
func (mr *MockFeedbackRepositoryMockRecorder) CreateFeedback(feedback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeedback", reflect.TypeOf((*MockFeedbackRepository)(nil).CreateFeedback), feedback)
}

// GetAllFeedbacks mocks base method.
func (m *MockFeedbackRepository) GetAllFeedbacks() ([]models.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFeedbacks")
	ret0, _ := ret[0].([]models.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFeedbacks indicates an expected call of GetAllFeedbacks.
func (mr *MockFeedbackRepositoryMockRecorder) GetAllFeedbacks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFeedbacks", reflect.TypeOf((*MockFeedbackRepository)(nil).GetAllFeedbacks))
}

// Save mocks base method.
func (m *MockFeedbackRepository) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFeedbackRepositoryMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFeedbackRepository)(nil).Save))
}
